#!/bin/sh
cd ${0%/*} || exit 1

nProcs=1
if[$# -ne 0]
	then nProcs=$1;
fi

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication createPatch -overwrite

cp -r backup_0 0

if[$nProcs -eq 1] ; then
	runApplication hy2Foam
else
	runApplication decomposePar -latestTime
	mpirun -np $nProcs hy2Foam -parallel > log.hy2Foam 2>&1
	runApplication reconstructPar -latestTime
fi
